---
- name: Create OWASP Nist Mirror Dir
  become: true
  file:
    path: "{{ owasp_dependency_check_mirror_dir }}"
    owner: root
    mode: "u=rwx,go=rx"
    group: root
    state: directory

- block:
    - name: "OWASP Group"
      become: true
      group:
        name: "{{ owasp_dependency_check_mirror_group }}"
        system: true

    - name: "OWASP User"
      become: true
      user:
        createhome: true
        group: "{{ owasp_dependency_check_mirror_group }}"
        home: "{{ owasp_dependency_check_mirror_home }}"
        name: "{{ owasp_dependency_check_mirror_user }}"
        shell: "/bin/bash"
        system: true
  when: owasp_dependency_check_mirror_manage_user

- name: Create OWASP Nist Mirror Cache Dir
  become: true
  file:
    path: "{{ owasp_dependency_check_mirror_cache }}"
    owner: "{{ owasp_dependency_check_mirror_user }}"
    mode: "u=rwx,go=rx"
    group: "{{ owasp_dependency_check_mirror_group }}"
    state: directory

- name: Package for maven_artifact
  become: true
  package:
    name: python-lxml
    state: present

- name: Retrieve Mirror Tool
  become: true
  maven_artifact:
    artifact_id: nist-data-mirror
    group_id: us.springett
    version: "{{ owasp_dependency_check_mirror_version }}"
    dest: "{{ owasp_dependency_check_mirror_dir }}/nist-data-mirror-{{ owasp_dependency_check_mirror_version }}.jar"
    repository_url: "{{ owasp_dependency_check_mirror_repository_url | default(omit) }}"
    state: present

- name: Tool Permissions
  become: true
  file:
    path: "{{ owasp_dependency_check_mirror_dir }}/nist-data-mirror-{{ owasp_dependency_check_mirror_version }}.jar"
    owner: root
    mode: "u=rw,go=r"
    group: root
    state: file

- name: Tool Symlink
  become: true
  file:
    path: "{{ owasp_dependency_check_mirror_dir }}/nist-data-mirror.jar"
    src: "{{ owasp_dependency_check_mirror_dir }}/nist-data-mirror-{{ owasp_dependency_check_mirror_version }}.jar"
    owner: root
    group: root
    force: true
    state: link

- name: Cron Script
  become: true
  template:
    dest: "/usr/local/bin/owasp_nist_mirror.sh"
    src: "owasp_nist_mirror.sh.j2"
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: Cron job
  become: true
  cron:
    name: "OWASP NIST Mirror"
    cron_file: owasp_nist_mirror
    user: "{{ owasp_dependency_check_mirror_user }}"
    special_time: daily
    job: "/usr/local/bin/owasp_nist_mirror.sh"
    state: present
