---
- git: 'https://github.com/geerlingguy/ansible-role-java.git'
  version: '1.9.5'
  dst: $MOLECULE_EPHEMERAL_DIRECTORY/roles/geerlingguy.java/
- git: 'https://github.com/geerlingguy/ansible-role-nginx.git'
  version: '2.7.0'
  dst: $MOLECULE_EPHEMERAL_DIRECTORY/roles/geerlingguy.nginx/
